
const Header = (event) => {
    return (
        <head>
            <title>Staffs Profile Management</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </head>
    )
}

export default Header;